const products = [
  {
    id: 1,
    name: "HADES REDEMPTION LONGSLEEVE",
    category: "tops",
    price: 550000,
    date: 5,
    sold: 20,
    featured: false,
    imgFront: "../img/f25.jpg",
    imgBack: "../img/b25.jpg",
  },
  {
    id: 2,
    name: "HADES RACING TEAM",
    category: "tops",
    price: 550000,
    date: 4,
    sold: 35,
    featured: true,
    imgFront: "../img/f26.jpg",
    imgBack: "../img/b26.jpg",
  },
  {
    id: 3,
    name: "HADES GLORY WASH TEE",
    category: "tops",
    price: 620000,
    date: 6,
    sold: 15,
    featured: false,
    imgFront: "../img/f27.jpg",
    imgBack: "../img/b27.jpg",
  },
  {
    id: 4,
    name: "HADES CAMO MESH TEE",
    category: "tops",
    price: 490000,
    date: 7,
    sold: 40,
    featured: true,
    imgFront: "../img/f28.jpg",
    imgBack: "../img/b28.jpg",
  },
  {
    id: 5,
    name: "HADES WILD MESH TEE",
    category: "tops",
    price: 490000,
    date: 3,
    sold: 18,
    featured: false,
    imgFront: "../img/f29.jpg",
    imgBack: "../img/b29.jpg",
  },
  {
    id: 6,
    name: "HADES OG TEE - BLACK",
    category: "tops",
    price: 450000,
    date: 8,
    sold: 60,
    featured: true,
    imgFront: "../img/f30.png",
    imgBack: "../img/b30.jpg",
  },
  {
    id: 7,
    name: "HADES LAST KISS LONGSLEEVE",
    category: "tops",
    price: 620000,
    date: 2,
    sold: 10,
    featured: false,
    imgFront: "../img/f31.jpeg",
    imgBack: "../img/b31.jpeg",
  },
  {
    id: 8,
    name: "HADES SAINT'S DAGGER TEE",
    category: "tops",
    price: 550000,
    date: 6,
    sold: 25,
    featured: false,
    imgFront: "../img/f32.jpg",
    imgBack: "../img/b32.jpg",
  },
  {
    id: 9,
    name: "HADES NOTYOURCRUSH WASH TEE - PINK",
    category: "tops",
    price: 550000,
    date: 9,
    sold: 45,
    featured: true,
    imgFront: "../img/f33.png",
    imgBack: "../img/b33.jpg",
  },
  {
    id: 10,
    name: "HADES HEARTLOCK CARO SHIRT",
    category: "tops",
    price: 790000,
    date: 4,
    sold: 12,
    featured: false,
    imgFront: "../img/f34.jpeg",
    imgBack: "../img/b34.jpeg",
  },
  {
    id: 11,
    name: "HADES EXPEDITION TEE",
    category: "tops",
    price: 580000,
    date: 7,
    sold: 30,
    featured: false,
    imgFront: "../img/f35.jpeg",
    imgBack: "../img/b35.jpeg",
  },
  {
    id: 12,
    name: "HADES URBAN LINES SHIRT - GREEN",
    category: "tops",
    price: 690000,
    date: 3,
    sold: 22,
    featured: false,
    imgFront: "../img/f36.jpeg",
    imgBack: "../img/b36.jpeg",
  },
  {
    id: 13,
    name: "HADES NIGHTSTRIKE LONGSLEEVE",
    category: "tops",
    price: 0,
    stock: 0,
    date: 1,
    sold: 5,
    featured: false,
    imgFront: "../img/f37.jpeg",
    imgBack: "../img/b37.jpg",
  },
  {
    id: 14,
    name: "HADES STAMPED KNITTED TEE - BLACK",
    category: "tops",
    price: 750000,
    date: 5,
    sold: 28,
    featured: false,
    imgFront: "../img/f38.jpeg",
    imgBack: "../img/b38.jpeg",
  },
  {
    id: 15,
    name: "HADES STAMPED KNITTED TEE - GREY",
    category: "tops",
    price: 750000,
    date: 6,
    sold: 19,
    featured: false,
    imgFront: "../img/f39.jpeg",
    imgBack: "../img/b39.jpeg",
  },
  {
    id: 16,
    name: "HADES DOUBLE EIGHT JERSEY",
    category: "tops",
    price: 990000,
    date: 8,
    sold: 55,
    featured: true,
    imgFront: "../img/f40.jpeg",
    imgBack: "../img/b40.jpeg",
  },
  {
    id: 17,
    name: "HADES DOUBLE EIGHT JERSEY",
    category: "tops",
    price: 960000,
    date: 3,
    sold: 36,
    featured: true,
    imgFront: "../img/f41.jpeg",
    imgBack: "../img/b41.jpg",
  },
  {
    id: 18,
    name: "HADES DOUBLE EIGHT JERSEY",
    category: "tops",
    price: 980000,
    date: 8,
    sold: 100,
    featured: true,
    imgFront: "../img/f42.jpeg",
    imgBack: "../img/b42.jpeg",
  },
  {
    id: 101,
    name: "HADES HUNTER KHAKI CAMO SHORTS",
    category: "bottoms",
    price: 790000,
    date: 6,
    sold: 25,
    featured: false,
    imgFront: "../img/f43.jpg",
    imgBack: "../img/b43.jpg",
  },
  {
    id: 102,
    name: "HADES TRIO STAR WASH JEAN SHORTS",
    category: "bottoms",
    price: 680000,
    date: 5,
    sold: 30,
    featured: true,
    imgFront: "../img/f44.jpg",
    imgBack: "../img/b44.jpg",
  },
  {
    id: 103,
    name: "HADES PLEATED CASUAL SHORTS",
    category: "bottoms",
    price: 620000,
    date: 7,
    sold: 18,
    featured: false,
    imgFront: "../img/f45.jpg",
    imgBack: "../img/b45.jpg",
  },
  {
    id: 104,
    name: "HADES WARFARE PIXEL PANTS",
    category: "bottoms",
    price: 850000,
    date: 8,
    sold: 40,
    featured: true,
    imgFront: "../img/f46.jpg",
    imgBack: "../img/b46.jpg",
  },
  {
    id: 105,
    name: "HADES RYKER JORT PANTS",
    category: "bottoms",
    price: 550000,
    date: 4,
    sold: 12,
    featured: false,
    imgFront: "../img/f47.jpg",
    imgBack: "../img/b47.jpg",
  },
  {
    id: 106,
    name: "HADES WASH BAGGY DENIM TROUSERS - BLUE",
    category: "bottoms",
    price: 950000,
    date: 9,
    sold: 35,
    featured: true,
    imgFront: "../img/f48.jpg",
    imgBack: "../img/b48.jpg",
  },
  {
    id: 107,
    name: "HADES WASH BAGGY DENIM TROUSERS - BLACK",
    category: "bottoms",
    price: 950000,
    date: 7,
    sold: 28,
    featured: false,
    imgFront: "../img/f49.jpg",
    imgBack: "../img/b49.jpg",
  },
  {
    id: 108,
    name: "HADES BLACKOUT DISTRESS WASH JEAN SHORTS",
    category: "bottoms",
    price: 680000,
    oldPrice: 900000,
    date: 5,
    sold: 22,
    featured: false,
    imgFront: "../img/f50.jpg",
    imgBack: "../img/b50.jpg",
  },
  {
    id: 109,
    name: "HADES HOME BODY CLUB PANTS",
    category: "bottoms",
    price: 720000,
    oldPrice: 1200000,
    date: 6,
    sold: 15,
    featured: false,
    imgFront: "../img/f51.jpg",
    imgBack: "../img/b51.jpg",
  },
  {
    id: 110,
    name: "HADES KHAKI CAMO MINI SKIRT",
    category: "bottoms",
    price: 490000,
    date: 8,
    sold: 20,
    featured: false,
    imgFront: "../img/f52.jpg",
    imgBack: "../img/b52.jpg",
  },
  {
    id: 111,
    name: "HADES PLAID DREAM PUMPKIN SHORTS - WHITE",
    category: "bottoms",
    price: 420000,
    date: 9,
    sold: 50,
    featured: true,
    imgFront: "../img/f53.jpg",
    imgBack: "../img/b53.jpg",
  },
  {
    id: 112,
    name: "HADES RAIDER KHAKI CAMO SHORTS",
    category: "bottoms",
    price: 790000,
    date: 7,
    sold: 27,
    featured: false,
    imgFront: "../img/f54.jpg",
    imgBack: "../img/b54.jpg",
  },
  {
    id: 113,
    name: "HADES DUNE RUPTURE WASH JEANS",
    category: "bottoms",
    price: 890000,
    date: 6,
    sold: 19,
    featured: false,
    imgFront: "../img/f55.jpeg",
    imgBack: "../img/b55.jpeg",
  },
  {
    id: 114,
    name: "HADES QUANTUM DRIFT WASH JEANS",
    category: "bottoms",
    price: 890000,
    date: 8,
    sold: 33,
    featured: true,
    imgFront: "../img/f56.jpeg",
    imgBack: "../img/b56.jpeg",
  },
  {
    id: 115,
    name: "HADES EITHER JEAN SHORTS",
    category: "bottoms",
    price: 790000,
    date: 5,
    sold: 17,
    featured: false,
    imgFront: "../img/f57.jpeg",
    imgBack: "../img/b57.jpeg",
  },
  {
    id: 116,
    name: "HADES STAR CRUSH WASH JEAN SHORTS",
    category: "bottoms",
    price: 720000,
    date: 7,
    sold: 26,
    featured: false,
    imgFront: "../img/f58.jpeg",
    imgBack: "../img/b58.jpeg",
  },
  {
    id: 117,
    name: "HADES STAR CRUSH WASH JEAN SHORTS",
    category: "bottoms",
    price: 720000,
    oldPrice: 1200000,
    date: 7,
    sold: 26,
    featured: false,
    imgFront: "../img/f59.jpg",
    imgBack: "../img/b59.jpg",
  },
  {
    id: 118,
    name: "HADES STAR CRUSH WASH JEAN SHORTS",
    category: "bottoms",
    price: 720000,
    date: 7,
    sold: 26,
    featured: false,
    imgFront: "../img/f60.jpg",
    imgBack: "../img/b60.jpeg",
  },
  {
    id: 116,
    name: "HADES STAR CRUSH WASH JEAN SHORTS",
    category: "bottoms",
    price: 720000,
    date: 7,
    sold: 26,
    featured: false,
    imgFront: "../img/f58.jpeg",
    imgBack: "../img/b58.jpeg",
  },
  {
    id: 201,
    name: "HADES HEAVENS CALL HOODIE ZIP - BLUE NAVY",
    category: "outerwear",
    price: 850000,
    oldPrice: 1000000,
    date: 8,
    sold: 40,
    featured: true,
    imgFront: "../img/f1.jpg",
    imgBack: "../img/b1.jpg",
  },
  {
    id: 202,
    name: "HADES HEAVENS CALL HOODIE ZIP - BLACK",
    category: "outerwear",
    price: 850000,
    date: 7,
    sold: 35,
    featured: false,
    imgFront: "../img/f2.jpg",
    imgBack: "../img/b2.jpg",
  },
  {
    id: 203,
    name: "HADES VOID DRIFTER ZIP HOODIE",
    category: "outerwear",
    price: 850000,
    date: 9,
    sold: 50,
    featured: true,
    imgFront: "../img/f3.jpeg",
    imgBack: "../img/b3.jpeg",
  },
  {
    id: 204,
    name: "HADES WASHED MATRIX JACKET",
    category: "outerwear",
    price: 1220000,
    date: 6,
    sold: 30,
    featured: false,
    imgFront: "../img/f4.jpeg",
    imgBack: "../img/b4.jpeg",
  },
  {
    id: 205,
    name: "HADES INDUSTRIAL EDGE HOODIE - BROWN",
    category: "outerwear",
    price: 1150000,
    date: 5,
    sold: 20,
    featured: false,
    imgFront: "../img/f5.jpeg",
    imgBack: "../img/b5.jpg",
  },
  {
    id: 206,
    name: "HADES INDUSTRIAL EDGE HOODIE - GREY",
    category: "outerwear",
    price: 1150000,
    date: 6,
    sold: 22,
    featured: false,
    imgFront: "../img/f6.jpeg",
    imgBack: "../img/b6.jpg",
  },
  {
    id: 207,
    name: "HADES TACTICAL CAMO JACKET",
    category: "outerwear",
    price: 890000,
    date: 7,
    sold: 28,
    featured: false,
    imgFront: "../img/f7.jpg",
    imgBack: "../img/b7.jpg",
  },
  {
    id: 208,
    name: "HADES REIGN VELVET JACKET",
    category: "outerwear",
    price: 850000,
    date: 8,
    sold: 33,
    featured: true,
    imgFront: "../img/f8.jpeg",
    imgBack: "../img/b8.jpeg",
  },
  {
    id: 209,
    name: "HADES ASTRAL DENIM JACKET",
    category: "outerwear",
    price: 1050000,
    date: 7,
    sold: 18,
    featured: false,
    imgFront: "../img/f9.jpeg",
    imgBack: "../img/b9.jpeg",
  },
  {
    id: 210,
    name: "HADES REBEL SWEATER KNIT - GREY",
    category: "outerwear",
    price: 950000,
    date: 6,
    sold: 26,
    featured: false,
    imgFront: "../img/f10.jpeg",
    imgBack: "../img/b10.jpeg",
  },
  {
    id: 211,
    name: "HADES REBEL SWEATER KNIT - PINK",
    category: "outerwear",
    price: 950000,
    stock: 0,
    date: 9,
    sold: 45,
    featured: true,
    imgFront: "../img/f12.jpeg",
    imgBack: "../img/b12.jpeg",
  },
  {
    id: 212,
    name: "HADES DARK MATTER DENIM JACKET",
    category: "outerwear",
    price: 1050000,
    date: 8,
    sold: 38,
    featured: false,
    imgFront: "../img/f13.jpeg",
    imgBack: "../img/b13.jpeg",
  },
  {
    id: 301,
    name: "HADES STRETCHY BOXER - BLACK/PACK",
    category: "underwear",
    price: 390000,
    date: 6,
    sold: 25,
    featured: false,
    imgFront: "../img/f61.jpg",
    imgBack: "../img/b61.jpg",
  },
  {
    id: 302,
    name: "HADES STRETCHY BOXER - WHITE/PACK",
    category: "underwear",
    price: 390000,
    date: 7,
    sold: 30,
    featured: true,
    imgFront: "../img/f62.jpg",
    imgBack: "../img/b62.jpg",
  },
  {
    id: 303,
    name: "HADES STRIPED BOXERS",
    category: "underwear",
    price: 280000,
    date: 5,
    sold: 18,
    featured: false,
    imgFront: "../img/f63.jpg",
    imgBack: "../img/b63.jpg",
  },
  {
    id: 401,
    name: "HADES HUMID WASTELAND BAG - BLACK",
    category: "bags",
    price: 750000,
    oldPrice: 900000,
    date: 7,
    sold: 20,
    featured: false,
    imgFront: "../img/f64.jpg",
    imgBack: "../img/b64.jpg",
  },
  {
    id: 402,
    name: "HADES VOYAGER BACKPACK",
    category: "bags",
    price: 850000,
    date: 8,
    sold: 35,
    featured: true,
    imgFront: "../img/f65.jpg",
    imgBack: "../img/b65.jpg",
  },
  {
    id: 403,
    name: "HADES QUILTED ARMOR BACKPACK",
    category: "bags",
    price: 850000,
    date: 6,
    sold: 28,
    featured: false,
    imgFront: "../img/f66.jpg",
    imgBack: "../img/b66.jpg",
  },
  {
    id: 404,
    name: "HADES NOMAD BACKPACK",
    category: "bags",
    price: 820000,
    date: 9,
    sold: 40,
    featured: true,
    imgFront: "../img/f67.jpeg",
    imgBack: "../img/b67.jpeg",
  },
  {
    id: 405,
    name: "BLACK BLOCK BACKPACK",
    category: "bags",
    price: 670000,
    date: 5,
    sold: 18,
    featured: false,
    imgFront: "../img/f68.jpg",
    imgBack: "../img/b68.jpg",
  },
  {
    id: 406,
    name: "HADES OBSIDIAN LEATHER BAG",
    category: "bags",
    price: 750000,
    date: 7,
    sold: 22,
    featured: false,
    imgFront: "../img/f69.jpg",
    imgBack: "../img/b69.jpg",
  },
  {
    id: 407,
    name: "HADES BACKPACK LEATHER 24",
    category: "bags",
    price: 670000,
    date: 6,
    sold: 25,
    featured: false,
    imgFront: "../img/f70.jpg",
    imgBack: "../img/b70.jpg",
  },
  {
    id: 501,
    name: "HADES CLOUD NINE SCARF",
    category: "accessories",
    price: 1220000,
    date: 9,
    sold: 15,
    featured: true,
    imgFront: "../img/f71.jpeg",
    imgBack: "../img/b71.jpeg",
  },
  {
    id: 502,
    name: "HADES CREST DAD CAP - BLACK",
    category: "accessories",
    price: 350000,
    date: 7,
    sold: 40,
    featured: true,
    imgFront: "../img/f72.jpeg",
    imgBack: "../img/b72.jpeg",
  },
  {
    id: 503,
    name: "HADES CREST DAD CAP - BLUE NAVY",
    category: "accessories",
    price: 350000,
    oldPrice: 500000,
    date: 6,
    sold: 35,
    featured: false,
    imgFront: "../img/f73.jpeg",
    imgBack: "../img/b73.jpeg",
  },
  {
    id: 504,
    name: "HADES DENIM CAMP CAP",
    category: "accessories",
    price: 420000,
    date: 8,
    sold: 28,
    featured: false,
    imgFront: "../img/f74.jpg",
    imgBack: "../img/b74.jpeg",
  },
  {
    id: 505,
    name: "HADES DISTRESSED DENIM CAP",
    category: "accessories",
    price: 350000,
    date: 5,
    sold: 22,
    featured: false,
    imgFront: "../img/f75.jpg",
    imgBack: "../img/b75.jpg",
  },
  {
    id: 506,
    name: "HADES DISTRICT 1 CAP",
    category: "accessories",
    price: 320000,
    date: 9,
    sold: 50,
    featured: true,
    imgFront: "../img/f76.jpg",
    imgBack: "../img/b76.jpg",
  },
  {
    id: 507,
    name: "HADES ICONIC STAR SNAPBACK",
    category: "accessories",
    price: 420000,
    oldPrice: 620000,
    date: 7,
    sold: 30,
    featured: false,
    imgFront: "../img/f77.jpg",
    imgBack: "../img/b77.jpg",
  },
  {
    id: 508,
    name: "HADES PROFILE ELLIPSE CAP",
    category: "accessories",
    price: 350000,
    date: 6,
    sold: 25,
    featured: false,
    imgFront: "../img/f78.jpg",
    imgBack: "../img/b78.jpg",
  },
];
